export const dataForCalendar = [
  // December
  {
    year: '2023',
    month: '12',
    day: '04',
    project: {
      projectName: 'Project Alpha',
      taskName: 'Analysis',
      hour: '1',
      color: '#87CEEB',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '05',
    project: {
      projectName: 'Client Bravo',
      taskName: 'Development',
      hour: '2',
      color: '#98FB98',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '06',
    project: {
      projectName: 'Project Gamma',
      taskName: 'Testing',
      hour: '3',
      color: '#E6E6FA',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '07',
    project: {
      projectName: 'Client Delta',
      taskName: 'Meeting',
      hour: '1',
      color: '#F5F5DC',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '08',
    project: {
      projectName: 'Project Epsilon',
      taskName: 'Documentation',
      hour: '2',
      color: '#C8A2C8',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '11',
    project: {
      projectName: 'Client Zeta',
      taskName: 'Analysis',
      hour: '3',
      color: '#87CEEB',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '12',
    project: {
      projectName: 'Project Theta',
      taskName: 'Development',
      hour: '1',
      color: '#98FB98',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '13',
    project: {
      projectName: 'Client Iota',
      taskName: 'Testing',
      hour: '2',
      color: '#E6E6FA',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '14',
    project: {
      projectName: 'Project Kappa',
      taskName: 'Meeting',
      hour: '1',
      color: '#F5F5DC',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '15',
    project: {
      projectName: 'Client Lambda',
      taskName: 'Documentation',
      hour: '3',
      color: '#C8A2C8',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '18',
    project: {
      projectName: 'Project Mu',
      taskName: 'Analysis',
      hour: '2',
      color: '#87CEEB',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '19',
    project: {
      projectName: 'Client Nu',
      taskName: 'Development',
      hour: '1',
      color: '#98FB98',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '20',
    project: {
      projectName: 'Project Xi',
      taskName: 'Testing',
      hour: '3',
      color: '#E6E6FA',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '21',
    project: {
      projectName: 'Client Omicron',
      taskName: 'Meeting',
      hour: '2',
      color: '#F5F5DC',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '22',
    project: {
      projectName: 'Project Pi',
      taskName: 'Documentation',
      hour: '1',
      color: '#C8A2C8',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '28',
    project: {
      projectName: 'Project Upsilon',
      taskName: 'Meeting',
      hour: '2',
      color: '#F5F5DC',
    },
  },
  {
    year: '2023',
    month: '12',
    day: '29',
    project: {
      projectName: 'Client Phi',
      taskName: 'Documentation',
      hour: '3',
      color: '#C8A2C8',
    },
  },
  // January
  {
    year: '2024',
    month: '01',
    day: '02',
    project: {
      projectName: 'Project Chi',
      taskName: 'Analysis',
      hour: '1',
      color: '#87CEEB',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '03',
    project: {
      projectName: 'Client Psi',
      taskName: 'Development',
      hour: '2',
      color: '#98FB98',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '04',
    project: {
      projectName: 'Project Omega',
      taskName: 'Testing',
      hour: '3',
      color: '#E6E6FA',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '05',
    project: {
      projectName: 'Client Alpha',
      taskName: 'Meeting',
      hour: '1',
      color: '#F5F5DC',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '08',
    project: {
      projectName: 'Project Beta',
      taskName: 'Documentation',
      hour: '2',
      color: '#C8A2C8',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '09',
    project: {
      projectName: 'Client Gamma',
      taskName: 'Analysis',
      hour: '3',
      color: '#87CEEB',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '10',
    project: {
      projectName: 'Project Delta',
      taskName: 'Development',
      hour: '1',
      color: '#98FB98',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '11',
    project: {
      projectName: 'Client Epsilon',
      taskName: 'Testing',
      hour: '2',
      color: '#E6E6FA',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '12',
    project: {
      projectName: 'Project Zeta',
      taskName: 'Meeting',
      hour: '1',
      color: '#F5F5DC',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '15',
    project: {
      projectName: 'Client Eta',
      taskName: 'Documentation',
      hour: '3',
      color: '#C8A2C8',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '16',
    project: {
      projectName: 'Project Theta',
      taskName: 'Analysis',
      hour: '2',
      color: '#87CEEB',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '17',
    project: {
      projectName: 'Client Iota',
      taskName: 'Development',
      hour: '1',
      color: '#98FB98',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '18',
    project: {
      projectName: 'Project Kappa',
      taskName: 'Testing',
      hour: '3',
      color: '#E6E6FA',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '19',
    project: {
      projectName: 'Client Lambda',
      taskName: 'Meeting',
      hour: '2',
      color: '#F5F5DC',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '22',
    project: {
      projectName: 'Project Mu',
      taskName: 'Documentation',
      hour: '1',
      color: '#C8A2C8',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '23',
    project: {
      projectName: 'Client Nu',
      taskName: 'Analysis',
      hour: '2',
      color: '#87CEEB',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '24',
    project: {
      projectName: 'Project Xi',
      taskName: 'Development',
      hour: '3',
      color: '#98FB98',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '25',
    project: {
      projectName: 'Client Omicron',
      taskName: 'Testing',
      hour: '1',
      color: '#E6E6FA',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '26',
    project: {
      projectName: 'Project Pi',
      taskName: 'Meeting',
      hour: '2',
      color: '#F5F5DC',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '29',
    project: {
      projectName: 'Client Rho',
      taskName: 'Documentation',
      hour: '3',
      color: '#C8A2C8',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '30',
    project: {
      projectName: 'Project Sigma',
      taskName: 'Analysis',
      hour: '1',
      color: '#87CEEB',
    },
  },
  {
    year: '2024',
    month: '01',
    day: '31',
    project: {
      projectName: 'Client Tau',
      taskName: 'Development',
      hour: '2',
      color: '#98FB98',
    },
  },
];
